$ANSIBLE_VAULT;1.1;AES256
61363938626638626637343135666234303435626131306332333335313364613635663339343035
3438656534623431653136383830333631643864346261340a616134363435383232376335383738
31343063366364396162333862373661353561343636383666343765396433386366333865376666
3066363936316263370a653333613232616630303831633631353866356230356137396334326133
36333461396265663237336463373331356562636531353332663563393538313564313166643362
33383835613834616237616663653736646539333637646531343664376261353964336136643266
616464626436373931386132306438363265
