services:
  postgres_db:
    image: postgres:13.22-trixie
    container_name: postgres_db
    restart: always
    profiles: ["release", "compile"]
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: AnalyticsDB
      TZ: "America/Mexico_City"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./backend/initdb:/docker-entrypoint-initdb.d
    networks:
      - backend_net

  influx_db:
    image: influxdb:2.7
    container_name: influx_db
    restart: always
    profiles: ["release", "compile"]
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2:/var/lib/influxdb2
    environment:
      - TZ=America/Mexico_City
    networks:
      - backend_net

  rsyslog:
    image: rsyslog/rsyslog:latest
    container_name: rsyslog
    restart: always
    profiles: ["release", "compile"]
    ports:
      - "0.0.0.0:514:514/udp"
      - "0.0.0.0:514:514/tcp"
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf:ro
    networks:
      - backend_net
    cap_add:
      - NET_BIND_SERVICE     # allow binding to <1024

  backend_aegis:
    image: aegis_backend
    container_name: aegis_backend
    profiles: ["release"]
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      ANSIBLE_PRIVATE_KEY_FILE: /root/.ssh/id_ed25519
    volumes:
      - ./backend/identity/id_ed25519:/root/.ssh/id_ed25519:ro
      - ./backend/identity/influx_db.json:/analytics/identity/influx_db.json:ro
      - ./backend/identity/postgres_db.json:/analytics/identity/postgres_db.json:ro
      - ./backend/identity/telegram.json:/analytics/identity/telegram.json:ro
      - ./backend/config.json:/analytics/config.json:ro
      - ./backend/ansible/:/analytics/ansible/
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - postgres_db
      - influx_db
      - rsyslog
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  postgres_data:
