services:
  postgres_db:
    image: postgres:13.22-trixie
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: AnalyticsDB
      TZ: "America/Mexico_City"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./backend/initdb:/docker-entrypoint-initdb.d

  influx_db:
    image: influxdb:2.7
    container_name: influx_db
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2:/var/lib/influxdb2
    environment:
      - TZ=America/Mexico_City

  rsyslog:
    image: rsyslog/rsyslog:latest
    container_name: rsyslog
    ports:
      - "514:514/udp"
      - "514:514/tcp"
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf:ro
    networks:
      - syslognet

networks:
  syslognet:
    driver: bridge

volumes:
  postgres_data:
