api:
  endpoint: "http://localhost:5050"
  topology_endpoint: "http://localhost:5050/api/topology"
  retries: 3
  retry_delay_s: 5
  timeout_s: 15

ui:
  natural_scrolling: true


debug:
  enable_canvas_interaction_logging: true
  enable_canvas_link_class_logging: false
  enable_topology_service_logging: false
  enable_drawer_logging: false