api:
  endpoint: "http://localhost:5050"
  topology_endpoint: "http://localhost:5050/api/topology"
  retries: 3
  retry_delay_s: 5
  timeout_s: 15

ui:
  natural_scrolling: false
  move_canvas_with: "mouse3"


debug:
  enable_canvas_interaction_logging: false
  enable_canvas_link_class_logging: false
  enable_topology_service_logging: false
  enable_drawer_logging: false
  enable_canvas_tab_logging: false