api:
  endpoint: "http://localhost:5050"
  topology_endpoint: "http://localhost:5050/api/topology"
  syslog_count_endpoint: "http://localhost:5050/api/syslog/message_count"
  retries: 3
  retry_delay_s: 5
  timeout_s: 15

ws:
  syslog_ws_endpoint: "ws://localhost:5050/ws/syslog"
  syslog_rt_ws_endpoint: "ws://localhost:5050/ws/syslog/realtime"
  alerts_rt_ws_endpoint: "ws://localhost:5050/ws/alerts/realtime"

syslog:
  max_buffer_lines: 254

ui:
  natural_scrolling: false
  move_canvas_with: "mouse3"

debug:
  enable_canvas_interaction_logging: false
  enable_canvas_link_class_logging: false
  enable_syslog_service_logging: false
  enable_topology_service_logging: false
  enable_drawer_logging: false
  enable_canvas_tab_logging: false
  enable_alert_service_logging: true