---
- name: Gather all facts
  hosts: all
  gather_facts: no
  strategy: free

  tasks:
    - name: Gather interface stats
      ansible.builtin.command: ip -s link
      register: iface_stats
      changed_when: false

    - name: Extract interface stats
      ansible.builtin.set_fact:
        ansible_manual_new_interface_stats: "{{ iface_stats.stdout }}"
